import { USER_ROLES } from '../constants/collections';

/**
 * RouteWise Central Route Registry
 * Defines metadata, permissions, document titles, categories, and breadcrumb hierarchies
 * for all Public and Authenticated Multi-Page Application (MPA) routes.
 */
export const ROUTE_REGISTRY = {
  // --- Public Routes ---
  '/': {
    path: '/',
    label: 'Home',
    title: 'RouteWise — School Transport & Bus Tracking Platform',
    roles: null,
    isPublic: true,
    category: 'Public',
    description: 'Real-time school transport, bus tracking, and student safety management.',
  },
  '/privacy': {
    path: '/privacy',
    label: 'Privacy Policy',
    title: 'RouteWise — Privacy Policy & Data Minimization',
    roles: null,
    isPublic: true,
    category: 'Public',
    description: 'Data minimization, telematics protection, and student privacy commitments.',
  },
  '/terms': {
    path: '/terms',
    label: 'Terms of Service',
    title: 'RouteWise — Terms of Service',
    roles: null,
    isPublic: true,
    category: 'Public',
    description: 'Acceptable use standards, transport safety commitments, and account integrity.',
  },
  '/login': {
    path: '/login',
    label: 'Sign In',
    title: 'Sign In — RouteWise Platform',
    roles: null,
    isPublic: true,
    category: 'Authentication',
    description: 'Secure authentication portal for parents, drivers, staff, and administrators.',
  },
  '/register': {
    path: '/register',
    label: 'Create Account',
    title: 'Register — RouteWise Platform',
    roles: null,
    isPublic: true,
    category: 'Authentication',
    description: 'Register for guardian, staff, or student account verification.',
  },
  '/unauthorized': {
    path: '/unauthorized',
    label: 'Access Restricted',
    title: 'Access Restricted — RouteWise Security',
    roles: null,
    isPublic: true,
    category: 'Security',
    description: 'Restricted area. Your account does not have sufficient clearance for this terminal.',
  },
  '/404': {
    path: '/404',
    label: 'Page Not Found',
    title: 'Route Not Found (404) — RouteWise',
    roles: null,
    isPublic: true,
    category: 'System',
    description: 'The requested route coordinates do not exist on the RouteWise network.',
  },

  // --- Super Admin Governance Routes ---
  '/super-admin': {
    path: '/super-admin',
    label: 'Governance Console',
    title: 'RouteWise — Super Admin Governance Dashboard',
    roles: [USER_ROLES.SUPER_ADMIN],
    category: 'Governance',
    parent: null,
    searchable: true,
    description: 'Executive system-wide metrics, institutional health, and global operations summary.',
  },
  '/super-admin/users': {
    path: '/super-admin/users',
    label: 'User Directory',
    title: 'RouteWise — System User Directory',
    roles: [USER_ROLES.SUPER_ADMIN],
    category: 'Access Control',
    parent: '/super-admin',
    searchable: true,
    description: 'System-wide account governance, suspension, activation, and role assignments.',
  },
  '/super-admin/users/:userId': {
    path: '/super-admin/users/:userId',
    label: 'User Account Dossier',
    title: 'RouteWise — User Account Details',
    roles: [USER_ROLES.SUPER_ADMIN],
    category: 'Access Control',
    parent: '/super-admin/users',
    searchable: false,
    description: 'Comprehensive account inspection, security metadata, and audit log history.',
  },
  '/super-admin/roles': {
    path: '/super-admin/roles',
    label: 'Roles & Permissions',
    title: 'RouteWise — Role Governance Matrix',
    roles: [USER_ROLES.SUPER_ADMIN],
    category: 'Access Control',
    parent: '/super-admin',
    searchable: true,
    description: 'Role permission matrix, access scopes, and privilege boundaries.',
  },
  '/super-admin/schools': {
    path: '/super-admin/schools',
    label: 'School Districts',
    title: 'RouteWise — Campus & School Management',
    roles: [USER_ROLES.SUPER_ADMIN],
    category: 'Institutions',
    parent: '/super-admin',
    searchable: true,
    description: 'Institutional scoping, campus profiles, principal contacts, and timezones.',
  },
  '/super-admin/configuration': {
    path: '/super-admin/configuration',
    label: 'Platform Configuration',
    title: 'RouteWise — Global Platform Configuration',
    roles: [USER_ROLES.SUPER_ADMIN],
    category: 'System Governance',
    parent: '/super-admin',
    searchable: true,
    description: 'District parameters, emergency hotlines, maintenance mode toggles, and operational defaults.',
  },
  '/super-admin/notifications': {
    path: '/super-admin/notifications',
    label: 'Dispatch Rules',
    title: 'RouteWise — Global Notification Rules',
    roles: [USER_ROLES.SUPER_ADMIN],
    category: 'System Governance',
    parent: '/super-admin',
    searchable: true,
    description: 'Global trip delay broadcasting rules, emergency alert channels, and EmailJS status.',
  },
  '/super-admin/audit-logs': {
    path: '/super-admin/audit-logs',
    label: 'Immutable Audit Trail',
    title: 'RouteWise — Immutable System Audit Logs',
    roles: [USER_ROLES.SUPER_ADMIN],
    category: 'Security & Compliance',
    parent: '/super-admin',
    searchable: true,
    description: 'Append-only ledger recording all state-changing operational and administrative actions.',
  },
  '/super-admin/security': {
    path: '/super-admin/security',
    label: 'Security & Threat Center',
    title: 'RouteWise — Platform Security & Threat Center',
    roles: [USER_ROLES.SUPER_ADMIN],
    category: 'Security & Compliance',
    parent: '/super-admin',
    searchable: true,
    description: 'Access restriction alerts, suspicious elevation attempts, and perimeter telemetry.',
  },
  '/super-admin/system-health': {
    path: '/super-admin/system-health',
    label: 'Infrastructure Health',
    title: 'RouteWise — Infrastructure & Service Health',
    roles: [USER_ROLES.SUPER_ADMIN],
    category: 'Platform Diagnostics',
    parent: '/super-admin',
    searchable: true,
    description: 'Real-time connectivity status for Firebase Auth, Firestore, EmailJS, and client WebGL.',
  },
  '/super-admin/activity': {
    path: '/super-admin/activity',
    label: 'Platform Activity',
    title: 'RouteWise — Administrative Activity Stream',
    roles: [USER_ROLES.SUPER_ADMIN],
    category: 'Platform Diagnostics',
    parent: '/super-admin',
    searchable: true,
    description: 'Chronological timeline of system modifications and administrative state changes.',
  },
  '/super-admin/analytics': {
    path: '/super-admin/analytics',
    label: 'Governance Analytics',
    title: 'RouteWise — System-Wide Analytics & Intelligence',
    roles: [USER_ROLES.SUPER_ADMIN],
    category: 'Governance',
    parent: '/super-admin',
    searchable: true,
    description: 'Executive cross-district operational metrics, trip reliability, and fleet health.',
  },
  '/super-admin/analytics/overview': {
    path: '/super-admin/analytics/overview',
    label: 'Analytics Overview',
    title: 'RouteWise — System Analytics Overview',
    roles: [USER_ROLES.SUPER_ADMIN],
    category: 'Governance',
    parent: '/super-admin/analytics',
    searchable: true,
    description: 'Cross-district intelligence summaries, KPIs, and operational flags.',
  },
  '/super-admin/analytics/communication': {
    path: '/super-admin/analytics/communication',
    label: 'Communication Analytics',
    title: 'RouteWise — Communication & Alert Analytics',
    roles: [USER_ROLES.SUPER_ADMIN],
    category: 'Governance',
    parent: '/super-admin/analytics',
    searchable: true,
    description: 'Dispatch bulletin volume, EmailJS attempt status, and broadcast telemetry.',
  },
  '/super-admin/profile': {
    path: '/super-admin/profile',
    label: 'Executive Profile',
    title: 'RouteWise — Super Admin Profile',
    roles: [USER_ROLES.SUPER_ADMIN],
    category: 'Account',
    parent: '/super-admin',
    searchable: true,
    description: 'Super Administrator personal profile, credentials, and contact details.',
  },
  '/super-admin/settings': {
    path: '/super-admin/settings',
    label: 'Governance Preferences',
    title: 'RouteWise — Governance Console Preferences',
    roles: [USER_ROLES.SUPER_ADMIN],
    category: 'Account',
    parent: '/super-admin',
    searchable: true,
    description: 'Console preferences, audit table pagination size, and session timeout alerts.',
  },
  '/super-admin/backups': {
    path: '/super-admin/backups',
    label: 'Disaster Backups',
    title: 'RouteWise — Disaster Backup & Recovery Console',
    roles: [USER_ROLES.SUPER_ADMIN],
    category: 'Governance',
    parent: '/super-admin',
    searchable: true,
    description: 'Platform backup manifests, age health SLA monitor, integrity check triggers, and manual snapshot staging.',
  },
  '/super-admin/backups/:backupId': {
    path: '/super-admin/backups/:backupId',
    label: 'Backup Manifest Details',
    title: 'RouteWise — Backup Manifest Inspection',
    roles: [USER_ROLES.SUPER_ADMIN],
    category: 'Governance',
    parent: '/super-admin/backups',
    searchable: false,
    description: 'Deep audit of backup checksums, resource payload counts, GCP bucket locations, and non-destructive restore dry-runs.',
  },
  '/super-admin/recovery': {
    path: '/super-admin/recovery',
    label: 'Recovery Bin',
    title: 'RouteWise — Operational Recovery Bin',
    roles: [USER_ROLES.SUPER_ADMIN],
    category: 'Governance',
    parent: '/super-admin',
    searchable: true,
    description: 'Administrative soft-deletion recycle bin with relationship validation and un-deletion capabilities.',
  },

  // --- Admin & Transport Manager Routes ---
  '/admin': {
    path: '/admin',
    label: 'Overview',
    title: 'RouteWise — Admin Dashboard',
    roles: [USER_ROLES.ADMIN, USER_ROLES.TRANSPORT_MANAGER],
    category: 'Overview',
    parent: null,
    searchable: true,
    description: 'High-level fleet status, active buses, and real-time operations summary.',
  },
  '/admin/tracking': {
    path: '/admin/tracking',
    label: 'Fleet Tracking',
    title: 'RouteWise — Live Fleet Tracking',
    roles: [USER_ROLES.ADMIN, USER_ROLES.TRANSPORT_MANAGER],
    category: 'Transport',
    parent: '/admin',
    searchable: true,
    description: 'Interactive map with live GPS telemetry, speed monitoring, and bus locations.',
  },
  '/admin/planning': {
    path: '/admin/planning',
    label: 'Planning Headquarters',
    title: 'RouteWise — Transport Planning Dashboard',
    roles: [USER_ROLES.ADMIN, USER_ROLES.TRANSPORT_MANAGER],
    category: 'Planning',
    parent: '/admin',
    searchable: true,
    description: 'Transport route planning overview, readiness audits, capacity monitoring, and conflict detection.',
  },
  '/admin/planning/routes': {
    path: '/admin/planning/routes',
    label: 'Route Corridors',
    title: 'RouteWise — Route Planning & Sequencing',
    roles: [USER_ROLES.ADMIN, USER_ROLES.TRANSPORT_MANAGER],
    category: 'Planning',
    parent: '/admin/planning',
    searchable: true,
    description: 'Design route corridors, sequence stop waypoints, and assign vehicles.',
  },
  '/admin/planning/schedules': {
    path: '/admin/planning/schedules',
    label: 'Fleet Schedules',
    title: 'RouteWise — Transport Schedules & Conflicts',
    roles: [USER_ROLES.ADMIN, USER_ROLES.TRANSPORT_MANAGER],
    category: 'Planning',
    parent: '/admin/planning',
    searchable: true,
    description: 'Configure recurring operating hours, operating days, and detect schedule overlaps.',
  },
  '/admin/planning/trips': {
    path: '/admin/planning/trips',
    label: 'Trip Dispatch Generator',
    title: 'RouteWise — Trip Dispatch Generator',
    roles: [USER_ROLES.ADMIN, USER_ROLES.TRANSPORT_MANAGER],
    category: 'Planning',
    parent: '/admin/planning',
    searchable: true,
    description: 'Preview and batch-generate individual operational trips from schedules.',
  },
  '/admin/fleet': {
    path: '/admin/fleet',
    label: 'Fleet Operations',
    title: 'RouteWise — Fleet Operations & Maintenance',
    roles: [USER_ROLES.ADMIN, USER_ROLES.TRANSPORT_MANAGER],
    category: 'Fleet',
    parent: '/admin',
    searchable: true,
    description: 'School bus inventory, mechanical readiness, maintenance logs, and compliance.',
  },
  '/admin/fleet/maintenance': {
    path: '/admin/fleet/maintenance',
    label: 'Vehicle Maintenance',
    title: 'RouteWise — Maintenance Management',
    roles: [USER_ROLES.ADMIN, USER_ROLES.TRANSPORT_MANAGER],
    category: 'Fleet',
    parent: '/admin/fleet',
    searchable: true,
    description: 'Track preventative servicing, mechanic work orders, and shop downtime.',
  },
  '/admin/fleet/inspections': {
    path: '/admin/fleet/inspections',
    label: 'Safety Inspections',
    title: 'RouteWise — Vehicle Safety Inspections',
    roles: [USER_ROLES.ADMIN, USER_ROLES.TRANSPORT_MANAGER],
    category: 'Fleet',
    parent: '/admin/fleet',
    searchable: true,
    description: 'Pre-trip walkaround audits, periodic mechanical checklists, and defect logs.',
  },
  '/admin/fleet/documents': {
    path: '/admin/fleet/documents',
    label: 'Documents & Expiry',
    title: 'RouteWise — Vehicle Documents & Expiry',
    roles: [USER_ROLES.ADMIN, USER_ROLES.TRANSPORT_MANAGER],
    category: 'Fleet',
    parent: '/admin/fleet',
    searchable: true,
    description: 'Vehicle registration, insurance policies, and annual inspection certificates.',
  },
  '/admin/fleet/compliance': {
    path: '/admin/fleet/compliance',
    label: 'Fleet Compliance',
    title: 'RouteWise — Fleet Compliance Matrix',
    roles: [USER_ROLES.ADMIN, USER_ROLES.TRANSPORT_MANAGER],
    category: 'Fleet',
    parent: '/admin/fleet',
    searchable: true,
    description: 'Deterministic operational compliance verification across all school vehicles.',
  },
  '/admin/analytics': {
    path: '/admin/analytics',
    label: 'Operational Analytics',
    title: 'RouteWise — Transport Analytics & Intelligence',
    roles: [USER_ROLES.ADMIN, USER_ROLES.TRANSPORT_MANAGER],
    category: 'Operations',
    parent: '/admin',
    searchable: true,
    description: 'Data-backed KPIs, fleet utilization, trip completion, and capacity analysis.',
  },
  '/admin/analytics/overview': {
    path: '/admin/analytics/overview',
    label: 'Analytics Overview',
    title: 'RouteWise — Operational Intelligence Overview',
    roles: [USER_ROLES.ADMIN, USER_ROLES.TRANSPORT_MANAGER],
    category: 'Operations',
    parent: '/admin/analytics',
    searchable: true,
    description: 'Executive KPI cards, delay rates, fleet uptime, and attention items.',
  },
  '/admin/analytics/routes': {
    path: '/admin/analytics/routes',
    label: 'Route Intelligence',
    title: 'RouteWise — Route Performance & Capacity Analytics',
    roles: [USER_ROLES.ADMIN, USER_ROLES.TRANSPORT_MANAGER],
    category: 'Operations',
    parent: '/admin/analytics',
    searchable: true,
    description: 'Corridor capacity utilization, delay bottlenecks, and passenger loads.',
  },
  '/admin/analytics/trips': {
    path: '/admin/analytics/trips',
    label: 'Trip Reliability',
    title: 'RouteWise — Trip Reliability & Delay Analytics',
    roles: [USER_ROLES.ADMIN, USER_ROLES.TRANSPORT_MANAGER],
    category: 'Operations',
    parent: '/admin/analytics',
    searchable: true,
    description: 'Schedule punctuality, delay duration, and trip cancellation audits.',
  },
  '/admin/analytics/fleet': {
    path: '/admin/analytics/fleet',
    label: 'Fleet Analytics',
    title: 'RouteWise — Fleet Reliability & Maintenance Analytics',
    roles: [USER_ROLES.ADMIN, USER_ROLES.TRANSPORT_MANAGER],
    category: 'Operations',
    parent: '/admin/analytics',
    searchable: true,
    description: 'Vehicle downtime, recurring shop maintenance, and pre-trip inspection logs.',
  },
  '/admin/analytics/attendance': {
    path: '/admin/analytics/attendance',
    label: 'Attendance Patterns',
    title: 'RouteWise — Attendance & Boarding Analytics',
    roles: [USER_ROLES.ADMIN, USER_ROLES.TRANSPORT_MANAGER],
    category: 'Operations',
    parent: '/admin/analytics',
    searchable: true,
    description: 'Verified boarding rates, student absences, and drop-off completion.',
  },
  '/admin/analytics/safety': {
    path: '/admin/analytics/safety',
    label: 'Safety Analytics',
    title: 'RouteWise — Safety & Incident Risk Analytics',
    roles: [USER_ROLES.ADMIN, USER_ROLES.TRANSPORT_MANAGER],
    category: 'Operations',
    parent: '/admin/analytics',
    searchable: true,
    description: 'Emergency alarms, hazard breakdowns, and investigation resolution velocity.',
  },
  '/admin/trips': {
    path: '/admin/trips',
    label: 'Trips & Dispatch',
    title: 'RouteWise — Trips & Dispatch Management',
    roles: [USER_ROLES.ADMIN, USER_ROLES.TRANSPORT_MANAGER],
    category: 'Transport',
    parent: '/admin',
    searchable: true,
    description: 'Manage scheduled, in-transit, and completed bus journeys.',
  },
  '/admin/routes': {
    path: '/admin/routes',
    label: 'Routes',
    title: 'RouteWise — Route Management',
    roles: [USER_ROLES.ADMIN, USER_ROLES.TRANSPORT_MANAGER],
    category: 'Transport',
    parent: '/admin',
    searchable: true,
    description: 'Configure pickup and drop-off transport corridors and schedules.',
  },
  '/admin/stops': {
    path: '/admin/stops',
    label: 'Stops',
    title: 'RouteWise — Transport Stops',
    roles: [USER_ROLES.ADMIN, USER_ROLES.TRANSPORT_MANAGER],
    category: 'Transport',
    parent: '/admin',
    searchable: true,
    description: 'Designated geographic pickup and drop-off waypoints.',
  },
  '/admin/buses': {
    path: '/admin/buses',
    label: 'Fleet Buses',
    title: 'RouteWise — Bus Fleet Management',
    roles: [USER_ROLES.ADMIN, USER_ROLES.TRANSPORT_MANAGER],
    category: 'Transport',
    parent: '/admin',
    searchable: true,
    description: 'School transport vehicle inventory, capacity, and mechanical status.',
  },
  '/admin/students': {
    path: '/admin/students',
    label: 'Students',
    title: 'RouteWise — Students Management',
    roles: [USER_ROLES.ADMIN, USER_ROLES.TRANSPORT_MANAGER],
    category: 'People',
    parent: '/admin',
    searchable: true,
    description: 'Manage student transport enrollments, guardian assignments, and cards.',
  },
  '/admin/parents': {
    path: '/admin/parents',
    label: 'Parents & Guardians',
    title: 'RouteWise — Guardian Directory',
    roles: [USER_ROLES.ADMIN, USER_ROLES.TRANSPORT_MANAGER],
    category: 'People',
    parent: '/admin',
    searchable: true,
    description: 'Verified guardian profiles and linked student associations.',
  },
  '/admin/drivers': {
    path: '/admin/drivers',
    label: 'Drivers & Operators',
    title: 'RouteWise — Drivers Directory',
    roles: [USER_ROLES.ADMIN, USER_ROLES.TRANSPORT_MANAGER],
    category: 'People',
    parent: '/admin',
    searchable: true,
    description: 'Certified bus operators, licenses, and route assignments.',
  },
  '/admin/attendance': {
    path: '/admin/attendance',
    label: 'Passenger Attendance',
    title: 'RouteWise — Attendance & Boarding Logs',
    roles: [USER_ROLES.ADMIN, USER_ROLES.TRANSPORT_MANAGER],
    category: 'Operations',
    parent: '/admin',
    searchable: true,
    description: 'Real-time boarding, drop-off, and absence verification audits.',
  },
  '/admin/notifications': {
    path: '/admin/notifications',
    label: 'Notifications Hub',
    title: 'RouteWise — Dispatch Notifications',
    roles: [USER_ROLES.ADMIN, USER_ROLES.TRANSPORT_MANAGER],
    category: 'Operations',
    parent: '/admin',
    searchable: true,
    description: 'Broadcast alerts, delay advisories, and system communications.',
  },
  '/admin/safety': {
    path: '/admin/safety',
    label: 'Safety & Emergency Center',
    title: 'RouteWise — Fleet Safety Command Center',
    roles: [USER_ROLES.ADMIN, USER_ROLES.TRANSPORT_MANAGER],
    category: 'Safety',
    parent: '/admin',
    searchable: true,
    description: 'Emergency protocol execution, active SOS response, and safety monitoring.',
  },
  '/admin/incidents': {
    path: '/admin/incidents',
    label: 'Fleet Incidents Register',
    title: 'RouteWise — Incidents Register',
    roles: [USER_ROLES.ADMIN, USER_ROLES.TRANSPORT_MANAGER],
    category: 'Safety',
    parent: '/admin/safety',
    searchable: true,
    description: 'Investigation log for mechanical, medical, weather, and traffic events.',
  },
  '/admin/incidents/:incidentId': {
    path: '/admin/incidents/:incidentId',
    label: 'Incident Details',
    title: 'RouteWise — Incident Investigation File',
    roles: [USER_ROLES.ADMIN, USER_ROLES.TRANSPORT_MANAGER],
    category: 'Safety',
    parent: '/admin/incidents',
    searchable: false,
    description: 'Comprehensive incident audit, responder notes, timeline, and actions.',
  },
  '/admin/emergency-contacts': {
    path: '/admin/emergency-contacts',
    label: 'Emergency Contacts',
    title: 'RouteWise — Emergency Contacts Directory',
    roles: [USER_ROLES.ADMIN, USER_ROLES.TRANSPORT_MANAGER],
    category: 'Safety',
    parent: '/admin/safety',
    searchable: true,
    description: 'Rapid-dial contacts for campus security, medical, and local emergency dispatch.',
  },
  '/admin/reports': {
    path: '/admin/reports',
    label: 'Reports & Analytics',
    title: 'RouteWise — Fleet Analytics & Reports',
    roles: [USER_ROLES.ADMIN, USER_ROLES.TRANSPORT_MANAGER],
    category: 'Analytics',
    parent: '/admin',
    searchable: true,
    description: 'Fleet operational intelligence, on-time rate, and compliance data.',
  },
  '/admin/reports/trips': {
    path: '/admin/reports/trips',
    label: 'Trip Performance Reports',
    title: 'RouteWise — Trip Reports',
    roles: [USER_ROLES.ADMIN, USER_ROLES.TRANSPORT_MANAGER],
    category: 'Analytics',
    parent: '/admin/reports',
    searchable: true,
    description: 'Detailed journey punctuality, duration metrics, and mileage summaries.',
  },
  '/admin/reports/attendance': {
    path: '/admin/reports/attendance',
    label: 'Attendance Audits',
    title: 'RouteWise — Attendance Reports',
    roles: [USER_ROLES.ADMIN, USER_ROLES.TRANSPORT_MANAGER],
    category: 'Analytics',
    parent: '/admin/reports',
    searchable: true,
    description: 'Historical passenger boarding rates and absence records.',
  },
  '/admin/reports/buses': {
    path: '/admin/reports/buses',
    label: 'Fleet Utilization Reports',
    title: 'RouteWise — Bus Fleet Reports',
    roles: [USER_ROLES.ADMIN, USER_ROLES.TRANSPORT_MANAGER],
    category: 'Analytics',
    parent: '/admin/reports',
    searchable: true,
    description: 'Vehicle utilization metrics, capacity loads, and operational cycles.',
  },
  '/admin/reports/routes': {
    path: '/admin/reports/routes',
    label: 'Route Efficiency Reports',
    title: 'RouteWise — Route Analytics',
    roles: [USER_ROLES.ADMIN, USER_ROLES.TRANSPORT_MANAGER],
    category: 'Analytics',
    parent: '/admin/reports',
    searchable: true,
    description: 'Stop density, transit congestion patterns, and route timing analysis.',
  },
  '/admin/reports/drivers': {
    path: '/admin/reports/drivers',
    label: 'Driver Performance Reports',
    title: 'RouteWise — Driver Reports',
    roles: [USER_ROLES.ADMIN, USER_ROLES.TRANSPORT_MANAGER],
    category: 'Analytics',
    parent: '/admin/reports',
    searchable: true,
    description: 'Shift completion, safety compliance, and operator punctuality audit.',
  },
  '/admin/reports/students': {
    path: '/admin/reports/students',
    label: 'Student Transit Reports',
    title: 'RouteWise — Student Transit Reports',
    roles: [USER_ROLES.ADMIN, USER_ROLES.TRANSPORT_MANAGER],
    category: 'Analytics',
    parent: '/admin/reports',
    searchable: true,
    description: 'Ridership records, zone distribution, and boarding compliance.',
  },
  '/admin/settings': {
    path: '/admin/settings',
    label: 'Settings Command Center',
    title: 'RouteWise — System Settings',
    roles: [USER_ROLES.ADMIN, USER_ROLES.TRANSPORT_MANAGER],
    category: 'System',
    parent: '/admin',
    searchable: true,
    description: 'Configure institutional parameters, alerts, security, and fleet preferences.',
  },
  '/admin/settings/profile': {
    path: '/admin/settings/profile',
    label: 'Administrator Profile',
    title: 'RouteWise — Staff Profile',
    roles: [USER_ROLES.ADMIN, USER_ROLES.TRANSPORT_MANAGER],
    category: 'System',
    parent: '/admin/settings',
    searchable: true,
    description: 'Personal contact credentials, avatar photo, and security details.',
  },
  '/admin/settings/transport': {
    path: '/admin/settings/transport',
    label: 'Transport Settings',
    title: 'RouteWise — Transport Configuration',
    roles: [USER_ROLES.ADMIN, USER_ROLES.TRANSPORT_MANAGER],
    category: 'System',
    parent: '/admin/settings',
    searchable: true,
    description: 'GPS sampling intervals, geofence radius, and speed warning limits.',
  },
  '/admin/settings/notifications': {
    path: '/admin/settings/notifications',
    label: 'Notification Settings',
    title: 'RouteWise — Notification Routing',
    roles: [USER_ROLES.ADMIN, USER_ROLES.TRANSPORT_MANAGER],
    category: 'System',
    parent: '/admin/settings',
    searchable: true,
    description: 'Email alert toggles, dispatch notifications, and guardian SMS priorities.',
  },
  '/admin/settings/system': {
    path: '/admin/settings/system',
    label: 'System Maintenance',
    title: 'RouteWise — System Controls',
    roles: [USER_ROLES.ADMIN],
    category: 'System',
    parent: '/admin/settings',
    searchable: true,
    description: 'Academic session dates, institution parameters, and cache resets.',
  },
  '/admin/settings/security': {
    path: '/admin/settings/security',
    label: 'Security & Audit Log',
    title: 'RouteWise — Security & Audit Log',
    roles: [USER_ROLES.ADMIN],
    category: 'System',
    parent: '/admin/settings',
    searchable: true,
    description: 'Session timeout thresholds, two-factor rules, and security events.',
  },

  // --- Parent Portal Routes ---
  '/parent': {
    path: '/parent',
    label: 'Transport Overview',
    title: 'RouteWise — Guardian Transport Overview',
    roles: [USER_ROLES.PARENT],
    category: 'Family Transport',
    parent: null,
    searchable: true,
    description: 'Real-time overview of your children’s current bus routes and arrival times.',
  },
  '/parent/children': {
    path: '/parent/children',
    label: 'My Children',
    title: 'RouteWise — Children Transport Profiles',
    roles: [USER_ROLES.PARENT],
    category: 'Family Transport',
    parent: '/parent',
    searchable: true,
    description: 'Assigned buses, pickup stops, and medical/safety notes for each registered child.',
  },
  '/parent/tracking': {
    path: '/parent/tracking',
    label: 'Live Route Tracker',
    title: 'RouteWise — Live Child Bus Tracking',
    roles: [USER_ROLES.PARENT],
    category: 'Family Transport',
    parent: '/parent',
    searchable: true,
    description: 'Live interactive map showing the exact GPS location of your child’s school bus.',
  },
  '/parent/trips': {
    path: '/parent/trips',
    label: 'Trip History',
    title: 'RouteWise — Family Journey History',
    roles: [USER_ROLES.PARENT],
    category: 'Family Transport',
    parent: '/parent',
    searchable: true,
    description: 'Review historical transit times, pickup confirmations, and past journey logs.',
  },
  '/parent/attendance': {
    path: '/parent/attendance',
    label: 'Child Attendance',
    title: 'RouteWise — Child Boarding & Attendance',
    roles: [USER_ROLES.PARENT],
    category: 'Family Transport',
    parent: '/parent',
    searchable: true,
    description: 'Live boarding and drop-off timestamps with absent/leave management.',
  },
  '/parent/safety': {
    path: '/parent/safety',
    label: 'Safety & Assistance',
    title: 'RouteWise — Guardian Safety & Support',
    roles: [USER_ROLES.PARENT],
    category: 'Family Transport',
    parent: '/parent',
    searchable: true,
    description: 'Emergency school dispatch lines, safety guidelines, and direct driver contact.',
  },
  '/parent/notifications': {
    path: '/parent/notifications',
    label: 'School Bulletins',
    title: 'RouteWise — Guardian Notifications',
    roles: [USER_ROLES.PARENT],
    category: 'Communications & Account',
    parent: '/parent',
    searchable: true,
    description: 'Real-time notifications regarding bus delays, arrivals, and school advisories.',
  },
  '/parent/profile': {
    path: '/parent/profile',
    label: 'Guardian Profile',
    title: 'RouteWise — Guardian Profile',
    roles: [USER_ROLES.PARENT],
    category: 'Communications & Account',
    parent: '/parent',
    searchable: true,
    description: 'Manage parent contact phone, primary residence address, and linked students.',
  },
  '/parent/settings': {
    path: '/parent/settings',
    label: 'Notification Settings',
    title: 'RouteWise — Notification Preferences',
    roles: [USER_ROLES.PARENT],
    category: 'Communications & Account',
    parent: '/parent',
    searchable: true,
    description: 'Configure arrival proximity radius, SMS alerts, and email notifications.',
  },

  // --- Driver Portal Routes ---
  '/driver': {
    path: '/driver',
    label: 'Driver Console',
    title: 'RouteWise — Driver Console',
    roles: [USER_ROLES.DRIVER],
    category: 'Trip Operations',
    parent: null,
    searchable: true,
    description: 'Active shift cockpit, start/finish journey controls, and bus telematics.',
  },
  '/driver/safety': {
    path: '/driver/safety',
    label: 'Safety & SOS Command',
    title: 'RouteWise — Driver Safety Command',
    roles: [USER_ROLES.DRIVER],
    category: 'Trip Operations',
    parent: '/driver',
    searchable: true,
    description: 'One-touch SOS broadcasting, breakdown alerts, and emergency contact list.',
  },
  '/driver/incidents': {
    path: '/driver/incidents',
    label: 'Report Incident',
    title: 'RouteWise — Report Transit Incident',
    roles: [USER_ROLES.DRIVER],
    category: 'Trip Operations',
    parent: '/driver',
    searchable: true,
    description: 'Quickly lodge road closures, minor delays, student incidents, or mechanical issues.',
  },
  '/driver/attendance': {
    path: '/driver/attendance',
    label: 'Student Attendance',
    title: 'RouteWise — Passenger Manifest & Attendance',
    roles: [USER_ROLES.DRIVER],
    category: 'Trip Operations',
    parent: '/driver',
    searchable: true,
    description: 'Mark student boarding, absent, and drop-off status at each designated stop.',
  },
  '/driver/tracking': {
    path: '/driver/tracking',
    label: 'Live GPS Broadcast',
    title: 'RouteWise — Driver GPS Transmission',
    roles: [USER_ROLES.DRIVER],
    category: 'Trip Operations',
    parent: '/driver',
    searchable: true,
    description: 'Monitor live device geolocation broadcasting status, accuracy, and telemetry.',
  },
  '/driver/trips': {
    path: '/driver/trips',
    label: 'Trips Roster',
    title: 'RouteWise — Assigned Trips Roster',
    roles: [USER_ROLES.DRIVER],
    category: 'Trip Operations',
    parent: '/driver',
    searchable: true,
    description: 'Daily schedule of assigned morning and afternoon school runs.',
  },
  '/driver/vehicle': {
    path: '/driver/vehicle',
    label: 'Assigned Vehicle',
    title: 'RouteWise — Assigned Vehicle & Safety',
    roles: [USER_ROLES.DRIVER],
    category: 'Trip Operations',
    parent: '/driver',
    searchable: true,
    description: 'View assigned bus specifications, conduct daily pre-trip checks, and report defects.',
  },
  '/driver/vehicle/inspection': {
    path: '/driver/vehicle/inspection',
    label: 'Pre-Trip Inspection',
    title: 'RouteWise — Pre-Trip Safety Checklist',
    roles: [USER_ROLES.DRIVER],
    category: 'Trip Operations',
    parent: '/driver/vehicle',
    searchable: true,
    description: 'Mandatory pre-trip vehicle walkaround safety checklist.',
  },
  '/driver/vehicle/issues': {
    path: '/driver/vehicle/issues',
    label: 'Report Defect',
    title: 'RouteWise — Report Vehicle Defect',
    roles: [USER_ROLES.DRIVER],
    category: 'Trip Operations',
    parent: '/driver/vehicle',
    searchable: true,
    description: 'Transmit vehicle mechanical or safety defect reports to fleet maintenance.',
  },
  '/driver/trips/:tripId': {
    path: '/driver/trips/:tripId',
    label: 'Active Trip Console',
    title: 'RouteWise — Active Trip Details',
    roles: [USER_ROLES.DRIVER],
    category: 'Trip Operations',
    parent: '/driver/trips',
    searchable: false,
    description: 'Real-time turn-by-turn stop guidance and student manifest for this trip.',
  },
  '/driver/route': {
    path: '/driver/route',
    label: 'Route & Stops',
    title: 'RouteWise — Route Waypoints & Navigation',
    roles: [USER_ROLES.DRIVER],
    category: 'Trip Operations',
    parent: '/driver',
    searchable: true,
    description: 'Detailed sequence of assigned stops, scheduled arrival windows, and maps.',
  },
  '/driver/students': {
    path: '/driver/students',
    label: 'Passenger Manifest',
    title: 'RouteWise — Driver Passenger Manifest',
    roles: [USER_ROLES.DRIVER],
    category: 'Trip Operations',
    parent: '/driver',
    searchable: true,
    description: 'Complete student roll, assigned stops, emergency notes, and parent phones.',
  },
  '/driver/notifications': {
    path: '/driver/notifications',
    label: 'Dispatch Bulletins',
    title: 'RouteWise — Dispatch Notifications',
    roles: [USER_ROLES.DRIVER],
    category: 'Communications & Account',
    parent: '/driver',
    searchable: true,
    description: 'School transport announcements, roadwork alerts, and dispatcher instructions.',
  },
  '/driver/profile': {
    path: '/driver/profile',
    label: 'Operator Profile',
    title: 'RouteWise — Driver Profile',
    roles: [USER_ROLES.DRIVER],
    category: 'Communications & Account',
    parent: '/driver',
    searchable: true,
    description: 'Commercial driver license details, vehicle assignment, and contact info.',
  },
  '/driver/settings': {
    path: '/driver/settings',
    label: 'Console Preferences',
    title: 'RouteWise — Driver Preferences',
    roles: [USER_ROLES.DRIVER],
    category: 'Communications & Account',
    parent: '/driver',
    searchable: true,
    description: 'Audio prompt toggles, night mode display, and GPS battery saver options.',
  },

  // --- Student Portal Routes ---
  '/student': {
    path: '/student',
    label: 'Student Dashboard',
    title: 'RouteWise — Student Transit Pass',
    roles: [USER_ROLES.STUDENT],
    category: 'My Transit',
    parent: null,
    searchable: true,
    description: 'Next bus departure times, route status, and digital boarding card.',
  },
  '/student/safety': {
    path: '/student/safety',
    label: 'Rider Safety',
    title: 'RouteWise — Student Rider Safety',
    roles: [USER_ROLES.STUDENT],
    category: 'My Transit',
    parent: '/student',
    searchable: true,
    description: 'Safe bus boarding tips, what to do in delays, and school emergency hotline.',
  },
  '/student/attendance': {
    path: '/student/attendance',
    label: 'My Attendance',
    title: 'RouteWise — My Transit Attendance',
    roles: [USER_ROLES.STUDENT],
    category: 'My Transit',
    parent: '/student',
    searchable: true,
    description: 'Your logged morning and afternoon bus boarding history.',
  },
  '/student/transport': {
    path: '/student/transport',
    label: 'My Bus & Route',
    title: 'RouteWise — My Bus & Route Information',
    roles: [USER_ROLES.STUDENT],
    category: 'My Transit',
    parent: '/student',
    searchable: true,
    description: 'Assigned bus number, driver name, pickup stop, and journey map.',
  },
  '/student/trips': {
    path: '/student/trips',
    label: 'My Trips',
    title: 'RouteWise — My Bus Trips',
    roles: [USER_ROLES.STUDENT],
    category: 'My Transit',
    parent: '/student',
    searchable: true,
    description: 'Track today’s upcoming and historical rides to and from school.',
  },
  '/student/trips/:tripId': {
    path: '/student/trips/:tripId',
    label: 'Trip Details',
    title: 'RouteWise — Journey Details',
    roles: [USER_ROLES.STUDENT],
    category: 'My Transit',
    parent: '/student/trips',
    searchable: false,
    description: 'Live trip status, remaining stops, and estimated drop-off time.',
  },
  '/student/notifications': {
    path: '/student/notifications',
    label: 'School Notices',
    title: 'RouteWise — Student Transport Notices',
    roles: [USER_ROLES.STUDENT],
    category: 'Account & Settings',
    parent: '/student',
    searchable: true,
    description: 'Important updates regarding school bus schedules and weather delays.',
  },
  '/student/profile': {
    path: '/student/profile',
    label: 'My Transit Pass',
    title: 'RouteWise — Digital Student Pass',
    roles: [USER_ROLES.STUDENT],
    category: 'Account & Settings',
    parent: '/student',
    searchable: true,
    description: 'Student identification card, grade level, and transport zone information.',
  },
  '/student/settings': {
    path: '/student/settings',
    label: 'Alert Preferences',
    title: 'RouteWise — Student Alert Preferences',
    roles: [USER_ROLES.STUDENT],
    category: 'Account & Settings',
    parent: '/student',
    searchable: true,
    description: 'Choose when to receive notifications before your bus arrives at your stop.',
  },
};

/**
 * Helper to match an active pathname against registered routes
 * Handles dynamic parameters like /driver/trips/:tripId or /admin/incidents/:incidentId
 */
export function getRouteMetadata(pathname) {
  if (ROUTE_REGISTRY[pathname]) {
    return ROUTE_REGISTRY[pathname];
  }

  // Check dynamic route patterns
  for (const [pattern, meta] of Object.entries(ROUTE_REGISTRY)) {
    if (pattern.includes(':')) {
      const regexPattern = '^' + pattern.replace(/:[a-zA-Z0-9_-]+/g, '([^/]+)') + '$';
      const regex = new RegExp(regexPattern);
      if (regex.test(pathname)) {
        return meta;
      }
    }
  }

  // Fallback default
  return {
    path: pathname,
    label: pathname.split('/').filter(Boolean).pop() || 'RouteWise',
    title: 'RouteWise Platform',
    roles: null,
    category: 'General',
    parent: null,
  };
}

/**
 * Generate breadcrumb trail array from a given pathname
 * Returns [{ path, label, isCurrent }]
 */
export function generateBreadcrumbTrail(pathname, role) {
  const trail = [];
  let current = getRouteMetadata(pathname);

  // Guard against loops with a safety counter
  const visited = new Set();
  let currMeta = current;

  while (currMeta && !visited.has(currMeta.path)) {
    visited.add(currMeta.path);
    trail.unshift({
      path: currMeta.path.includes(':') ? pathname : currMeta.path,
      label: currMeta.label,
    });

    if (currMeta.parent && ROUTE_REGISTRY[currMeta.parent]) {
      currMeta = ROUTE_REGISTRY[currMeta.parent];
    } else {
      break;
    }
  }

  // If the trail has only 1 item and it's not the portal root, prepend portal root
  if (trail.length === 1 && !['/super-admin', '/admin', '/parent', '/driver', '/student'].includes(pathname)) {
    const portalPath = pathname.startsWith('/super-admin')
      ? '/super-admin'
      : pathname.startsWith('/admin')
      ? '/admin'
      : pathname.startsWith('/parent')
      ? '/parent'
      : pathname.startsWith('/driver')
      ? '/driver'
      : pathname.startsWith('/student')
      ? '/student'
      : null;

    if (portalPath && ROUTE_REGISTRY[portalPath] && portalPath !== pathname) {
      trail.unshift({
        path: portalPath,
        label: ROUTE_REGISTRY[portalPath].label,
      });
    }
  }

  return trail.map((item, idx) => ({
    ...item,
    isCurrent: idx === trail.length - 1,
  }));
}

/**
 * Get all searchable routes permitted for a given user role
 */
export function getSearchableRoutesForRole(role) {
  return Object.values(ROUTE_REGISTRY).filter((route) => {
    if (!route.searchable) return false;
    if (route.isPublic) return false; // Private/dashboard search only
    if (!route.roles) return true;
    if (role === USER_ROLES.SUPER_ADMIN) return true; // Super Admin can search all routes
    if (role === USER_ROLES.ADMIN) {
      // Admin cannot search super-admin routes
      return route.roles.includes(USER_ROLES.ADMIN);
    }
    return route.roles.includes(role);
  });
}
